version: '3'

services:

    database:
        image: mysql:8
        ports:
            - "33062:3306"
        environment:
            MYSQL_ROOT_USER: blogspa
            MYSQL_ROOT_PASSWORD: blogspa
            MYSQL_DATABASE: blogspa
            MYSQL_USER: blogspa
            MYSQL_PASSWORD: blogspa

    mailer:
        image: schickling/mailcatcher
        ports: [1025, 1080]

    redis:
        image: redis:5-alpine
        ports: [6379]

    rabbitmq:
        image: rabbitmq:3.7-management
        ports: [5672, 15672]
